In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  
import emcee
import math
import matplotlib



In [2]:
local_sol = ['S0927', 'S1306', 'U0148', 'U1319']
sol_redshift = np.array([5.79, 5.99, 5.98, 6.13])
real = pd.read_csv('/Users/alex/Desktop/final_files/correct_precision/paper2/all_components_file_with_completeness_sep11.csv')

# redshift path variables
light = 299792.458
omega_M = 0.308
omega_L = 1.0 - omega_M



In [51]:
# OI
lambda_location = 1302.1685
lyalpha = 1215.67


delta_lambda = lyalpha*3000.0/light  
max_redshift = ((1.0 + sol_redshift)*lyalpha - delta_lambda)/lyalpha - 1.0

min_redshift = (1.0 + sol_redshift)*lyalpha/lambda_location - 1.0


# now get the total path
dx1 = 0.0
dz1 = 0.0
for z in range(0, len(min_redshift)):
    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + max_redshift[z]), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + min_redshift[z]), 3.) + omega_L), 0.5)
    dx1 = dx1 + (Xmax - Xmin)
    dz1 = dz1 + (max_redshift[z] - min_redshift[z])

print(dx1, dz1)  



8.44623132528 1.81260748213


In [54]:
# CII
lambda_location = 1334.5323
lyalpha = 1215.67


delta_lambda = lyalpha*3000.0/light  
max_redshift = ((1.0 + sol_redshift)*lyalpha - delta_lambda)/lyalpha - 1.0

min_redshift = (1.0 + sol_redshift)*lyalpha/lambda_location - 1.0


# now get the total path
dx1 = 0.0
dz1 = 0.0
for z in range(0, len(min_redshift)):
    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + max_redshift[z]), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + min_redshift[z]), 3.) + omega_L), 0.5)
    dx1 = dx1 + (Xmax - Xmin)
    dz1 = dz1 + (max_redshift[z] - min_redshift[z])

dx1

11.319587513372273

In [52]:
# SiII
lambda_location = 1526.70698
lyalpha = 1215.67


delta_lambda = lyalpha*3000.0/light  
max_redshift = ((1.0 + sol_redshift)*lyalpha - delta_lambda)/lyalpha - 1.0

min_redshift = (1.0 + sol_redshift)*lyalpha/lambda_location - 1.0

print(min_redshift)
print(max_redshift)
# now get the total path
dx1 = 0.0
dx2 = 0.0
for z in range(0, len(min_redshift)):
    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + 5.0), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + min_redshift[z]), 3.) + omega_L), 0.5)
    dx1 = dx1 + (Xmax - Xmin)

    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + max_redshift[z]), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + 5.00), 3.) + omega_L), 0.5)
    dx2 = dx2 + (Xmax - Xmin)




print(dx1, dx2)

[ 4.406669    4.56592287  4.55796018  4.67740058]
[ 5.77999308  5.97999308  5.96999308  6.11999308]
7.70770499603 17.5939435277


In [53]:
# AlII
lambda_location = 1670.7886
lyalpha = 1215.67


delta_lambda = lyalpha*3000.0/light  
max_redshift = ((1.0 + sol_redshift)*lyalpha - delta_lambda)/lyalpha - 1.0

min_redshift = (1.0 + sol_redshift)*lyalpha/lambda_location - 1.0

print(min_redshift)
print(max_redshift)
# now get the total path
dx1 = 0.0
dx2 = 0.0
for z in range(0, len(min_redshift)):
    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + 5.0), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + min_redshift[z]), 3.) + omega_L), 0.5)
    dx1 = dx1 + (Xmax - Xmin)

    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + max_redshift[z]), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + 5.00), 3.) + omega_L), 0.5)
    dx2 = dx2 + (Xmax - Xmin)


print(dx1, dx2)

[ 3.94042113  4.08594163  4.07866561  4.18780599]
[ 5.77999308  5.97999308  5.96999308  6.11999308]
15.6025827843 17.5939435277


In [48]:
# Fe2
lambda_location = 1260.17
lyalpha = 1215.67


delta_lambda = lyalpha*3000.0/light  
max_redshift = ((1.0 + sol_redshift)*lyalpha - delta_lambda)/lyalpha - 1.0

min_redshift = (1.0 + sol_redshift)*lyalpha/lambda_location - 1.0
print(min_redshift)
print(max_redshift)
# now get the total path
dx1 = 0.0
dz1 = 0.0
for z in range(0, len(min_redshift)):
    Xmax = (2./3./omega_M)*pow((omega_M*pow((1. + max_redshift[z]), 3.) + omega_L), 0.5)
    Xmin = (2./3./omega_M)*pow((omega_M*pow((1. + min_redshift[z]), 3.) + omega_L), 0.5)
    dx1 = dx1 + (Xmax - Xmin)
    dz1 = dz1 + (max_redshift[z] - min_redshift[z])



[ 5.55022679  5.74316426  5.73351738  5.87822048]
[ 5.77999308  5.97999308  5.96999308  6.11999308]


In [90]:
# S0927
# this is not one of Valentina's objects
S0927 = real.loc[(real.system == 21) & (real.sol == 'S0927')]

c4 = S0927.loc[(S0927.rest_l < 1550) & (S0927.element == 'CIV')]
si4 = S0927.loc[(S0927.rest_l < 1400) & (S0927.element == 'SiIV')]

a = [c4, si4]
S0 = pd.concat(a)
print(pow(10, np.array(si4.cd_high))/pow(10, np.array(c4.cd_high)),  
      pow(10, np.array(si4.c_d))/pow(10, np.array(c4.c_d)), 
      pow(10, np.array(si4.cd_low))/pow(10, np.array(c4.cd_low)))

pow(10, np.array(si4.cd_high))

[ 0.41001524] [ 0.40944917] [ 0.41266725]


array([  1.98198334e+13])

In [13]:
2/(4.46+11.32), 2**0.5/(4.46+11.32)

(0.12674271229404308, 0.08962063132909348)

In [92]:
# U0148
# this is not one of Valentina's objects
U0148 = real.loc[(real.system == 15)]

c4 = U0148.loc[(U0148.rest_l < 1550) & (U0148.element == 'CIV') & (U0148.sol == 'U0148')]
si4 = U0148.loc[(U0148.rest_l < 1400) & (U0148.element == 'SiIV') & (U0148.sol == 'U0148')]

a = [c4, si4]
U0 = pd.concat(a)
print(pow(10, np.array(si4.cd_high))/pow(10, np.array(c4.cd_high)),  
      pow(10, np.array(si4.c_d))/pow(10, np.array(c4.c_d)), 
      pow(10, np.array(si4.cd_low))/pow(10, np.array(c4.cd_low)))




[ 0.1157444] [ 0.07502396] [ 0.05385177]


In [93]:
# U1319
U1319 = real.loc[(real.system == 14) |
                 (real.system == 16) |
                 (real.system == 18) ]

c4 = U1319.loc[(U1319.rest_l < 1550) & (U1319.element == 'CIV') & (U1319.sol == 'U1319')]
si4 = U1319.loc[(U1319.rest_l < 1400) & (U1319.element == 'SiIV') & (U1319.sol == 'U1319')]

a = [c4, si4]
U1 = pd.concat(a)