In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline  

In [2]:
mg2_2796 = 2796.3542699	
light = 299792.458
norm_factor = 1.9600132
omega_M = 0.308
omega_L = 1.0 - omega_M
H0 = 67.8/3.08567758e24 # centimeters  
little_h = 100./H0
ro_crit = 1.89000e-29# units are h^2 g cm^(-3)
amu = 1.66053892e-27 # 10^-27; kilograms
mass_mg2 = 24.30506# * amu ;* 1.e3 ; grams

norm = 4.26*pow(10, -22)


In [21]:
logN_values = np.array([12.8, 12.57, 13.4, 13.1])
logN_errors = np.array([0.2, 0.07, 0.6, 0.1])
# now exclude the 5.95 system because W2796 > 0.3A
logN_values = np.array([12.8, 12.57, 13.4])
logN_errors = np.array([0.2, 0.07, 0.6])

deltax = 3.9

In [22]:
totalN = pow(10, logN_values )
totalN_plus  = pow(10, logN_values+logN_errors)
totalN_minus = pow(10, logN_values-logN_errors)

In [23]:
totalN_minus, totalN, totalN_plus

(array([  3.98107171e+12,   3.16227766e+12,   6.30957344e+12]),
 array([  6.30957344e+12,   3.71535229e+12,   2.51188643e+13]),
 array([  1.00000000e+13,   4.36515832e+12,   1.00000000e+14]))

In [24]:
omega = norm*sum(totalN)/deltax
omega_plus = norm*sum(totalN_plus)/deltax
omega_minus = norm*sum(totalN_minus)/deltax

In [25]:
omega_minus, omega, omega_plus

(1.4694731069936566e-09, 3.8387832209411294e-09, 1.2492194216754644e-08)

In [28]:
# now think a bit about completeness (as an average) resulting from d2n/dzdw value
cbar = 19.1/10.91
print(cbar)
# now adjust omega values
cbar*omega_minus, cbar*omega, cbar*omega_plus

1.7506874427131074


(2.5725881158184093e-09, 6.7205095801994115e-09, 2.1869927547205657e-08)